<a href="https://colab.research.google.com/github/Raman-Git1/LSTM/blob/main/LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
faqs = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Tanisha is a cute little piddi who like to dance?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts([faqs])

In [ ]:
len(tokenizer.word_index)

288

In [ ]:
input_sequences =[]
for sentence in faqs.split('\n'):
  tokenized_words=tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_words)):
    input_sequences.append(tokenized_words[:i+1])

In [ ]:
input_sequences

[[92, 1],
 [92, 1, 13],
 [11, 6],
 [11, 6, 1],
 [11, 6, 1, 12],
 [11, 6, 1, 12, 42],
 [11, 6, 1, 12, 42, 14],
 [11, 6, 1, 12, 42, 14, 43],
 [11, 6, 1, 12, 42, 14, 43, 53],
 [11, 6, 1, 12, 42, 14, 43, 53, 68],
 [11, 6, 1, 12, 42, 14, 43, 53, 68, 13],
 [11, 6, 1, 12, 42, 14, 43, 53, 68, 13, 147],
 [11, 6, 1, 12, 42, 14, 43, 53, 68, 13, 147, 148],
 [1, 12],
 [1, 12, 93],
 [1, 12, 93, 5],
 [1, 12, 93, 5, 44],
 [1, 12, 93, 5, 44, 27],
 [1, 12, 93, 5, 44, 27, 94],
 [1, 12, 93, 5, 44, 27, 94, 28],
 [1, 12, 93, 5, 44, 27, 94, 28, 2],
 [1, 12, 93, 5, 44, 27, 94, 28, 2, 8],
 [1, 12, 93, 5, 44, 27, 94, 28, 2, 8, 3],
 [1, 12, 93, 5, 44, 27, 94, 28, 2, 8, 3, 26],
 [1, 12, 93, 5, 44, 27, 94, 28, 2, 8, 3, 26, 44],
 [1, 12, 93, 5, 44, 27, 94, 28, 2, 8, 3, 26, 44, 69],
 [1, 12, 93, 5, 44, 27, 94, 28, 2, 8, 3, 26, 44, 69, 7],
 [1, 12, 93, 5, 44, 27, 94, 28, 2, 8, 3, 26, 44, 69, 7, 29],
 [1, 12, 93, 5, 44, 27, 94, 28, 2, 8, 3, 26, 44, 69, 7, 29, 70],
 [1, 12, 93, 5, 44, 27, 94, 28, 2, 8, 3, 26, 44, 69, 7

In [ ]:
max_len=max([len(x) for x in input_sequences])
max_len

57

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_sequences=pad_sequences(input_sequences,maxlen=max_len,padding='pre')
padded_sequences

array([[  0,   0,   0, ...,   0,  92,   1],
       [  0,   0,   0, ...,  92,   1,  13],
       [  0,   0,   0, ...,   0,  11,   6],
       ...,
       [  0,   0,   0, ..., 285,  18, 286],
       [  0,   0,   0, ...,  18, 286, 287],
       [  0,   0,   0, ..., 286, 287, 288]], dtype=int32)

In [ ]:
X=padded_sequences[:,:-1]
X

array([[  0,   0,   0, ...,   0,   0,  92],
       [  0,   0,   0, ...,   0,  92,   1],
       [  0,   0,   0, ...,   0,   0,  11],
       ...,
       [  0,   0,   0, ...,   0, 285,  18],
       [  0,   0,   0, ..., 285,  18, 286],
       [  0,   0,   0, ...,  18, 286, 287]], dtype=int32)

In [ ]:
y=padded_sequences[:,-1]
y

array([  1,  13,   6,   1,  12,  42,  14,  43,  53,  68,  13, 147, 148,
        12,  93,   5,  44,  27,  94,  28,   2,   8,   3,  26,  44,  69,
         7,  29,  70,  45,   6,   1,  71,  72,   7,   1,  12,  71,  72,
         7,   1,  12,   6,  54,  73,  30,   1,  71,  12,  42, 149,  70,
        54,  29,  55, 150,   6,   1,  95,   7,   1,  68,  13,   9,  19,
       151,   1, 152, 153, 154, 155,  14,  43,  53, 156,  14,  43,  53,
        14, 159,  74, 160,  97, 163,  10, 164,   1, 165,  95,  75,  76,
        99,  32,  15, 166,  32,  43,  53,  68,  13, 167, 100,  74,  20,
       101,  19,   5,  77,   7,  21,  13, 101,  20, 100,  74, 168,  56,
        46,   5,  77,   7,  21, 169, 170,  22,   4, 103,   5, 104,  33,
         9,   4,  47,   5, 105,   7,   1,  33,  16,  34,  17,  56, 171,
        30, 106,  22,   2, 103,   5,  33,   2,  10, 172, 173,  20,  57,
         1, 105,  10,   4, 174,   1, 107, 175,  21,  58, 177,   3,  78,
        45,  59,  45, 108, 178,   7,   1,  12,  76, 179,  58,  6

In [ ]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=289)



In [ ]:
y.shape

(865, 289)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [ ]:
model = Sequential()
model.add(Embedding(input_dim=289, output_dim=100, input_shape=(56,)))  # Use input_shape instead of input_length
model.add(LSTM(150))
model.add(Dense(289, activation='softmax'))


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 56, 100)        │        28,900 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 289)            │        43,639 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 223,139 (871.64 KB)

 Trainable params: 223,139 (871.64 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X,y,epochs=100)

Epoch 1/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 9s 192ms/step - accuracy: 0.0442 - loss: 5.5719
Epoch 2/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 3s 106ms/step - accuracy: 0.0650 - loss: 5.0846
Epoch 3/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 5s 91ms/step - accuracy: 0.0760 - loss: 5.0007
Epoch 4/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 6s 134ms/step - accuracy: 0.0731 - loss: 4.9739
Epoch 5/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 4s 87ms/step - accuracy: 0.0760 - loss: 4.9736
Epoch 6/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 3s 89ms/step - accuracy: 0.0748 - loss: 4.9004
Epoch 7/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 3s 89ms/step - accuracy: 0.0808 - loss: 4.8217
Epoch 8/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 4s 137ms/step - accuracy: 0.0952 - loss: 4.6710
Epoch 9/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 3s 90ms/step - accuracy: 0.1312 - loss: 4.4939
Epoch 10/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 3s 90ms/step - accuracy: 0.1444 - loss: 4.3821
Epoch 11/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 6s 105ms/step - accuracy: 0.1779 - loss: 4.0831
Epoch 12/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 5s 87ms

In [ ]:
import numpy as np


In [ ]:
import time
text = "learning curve"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step
learning curve and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
learning curve and nlp
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
learning curve and nlp be
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
learning curve and nlp be a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
learning curve and nlp be a part
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
learning curve and nlp be a part of
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
learning curve and nlp be a part of this
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
learning curve and nlp be a part of this program
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
learning curve and nlp be a part of this program what
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
learning curve and nlp be a part of this program what comes
